version: "3.9"
services:
  userscars:
    build:
      context: .
      dockerfile: Dockerfile.userscars
    ports:
      - "5050:5000"
    networks:
      - webnet
      
  firmsmarketscars:
    build:
      context: .
      dockerfile: Dockerfile.firms
    ports:
      - "8080:8000"
    networks:
      - webnet

networks:
  webnet: